name: CI

on:
  push:
    branches: [ main ]

jobs:
  test-codesniffer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: php-codesniffer
        uses: pipeline-components/php-codesniffer@v0.12.3
        with:
         options: -s -p --colors --standard=PHPCompatibility --extensions=php --runtime-set testVersion ${PHPVERSION}
